import React, { Component } from 'react';
import { I18n } from 'react-i18next';

class Login extends Component {
  render() {
    return (
      <I18n>{(t, { i18n }) => (<div className="shadow-lg p-5 bg-white rounded">

        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{fontSize: '11.0pt', fontFamily: '"Times New Roman",serif', color: '#3d3d3d'}}>As of May 01, 2018</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>These Terms of Use ("Terms") govern your rights and obligations regarding the use of&nbsp;Payklever's&nbsp;Software ("Software" or “App” which may mean a mobile site and/or mobile application) and service (both collectively referred to as the "</span><span style={{fontSize: '11.0pt', color: '#3d3d3d'}}>&nbsp;</span><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>Service</span></strong><span style={{fontSize: '11.0pt', color: '#3d3d3d'}}>&nbsp;</span><span style={{fontSize: '11.0pt', color: '#474747'}}>") on the Internet or in cellular media. These Terms constitute a fully binding agreement between Payklever, Inc. (including its affiliates and subsidiaries, "Payklever" or "We") the proprietor of all rights in and to the Service, and you. By using the Services , you consent to and agree to abide by the Terms and the Privacy Policy.</span> <span style={{fontSize: '11.0pt', color: '#474747'}}>If you do not agree to these Terms or any of its parts, then you are prohibited and must refrain from using the Service.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 36.0pt'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>&nbsp;</span></strong><span style={{fontSize: '11.0pt', color: '#474747'}}>(I) Payklever uses your access history to improve the quality of the Service it offers to you and&nbsp;to&nbsp;all of its users and to improve its operations and delivery of Services.&nbsp;&nbsp;This history is associated with your account and Devices. This history is retained by Payklever in accordance with the Privacy Policy.&nbsp;&nbsp;</span></p>
        <p style={{textAlign: 'justify', textIndent: '-18.0pt', background: 'white', margin: '0cm 0cm 6.75pt 42.0pt'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>Advertisements</span></strong><span style={{fontSize: '11.0pt', color: '#474747'}}>. Third party advertisements may appear on the Site from time to time. Payklever does not endorse these advertisements, and the advertisements are not intended to be, nor should they be, viewed by anyone operating the vehicle unless and until the vehicle comes to a complete stop, the vehicle is not running, and its operations no longer requires the attention of the Driver. &nbsp;</span></p>
        <p style={{textAlign: 'justify', textIndent: '-18.0pt', background: 'white', margin: '0cm 0cm 6.75pt 42.0pt'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>For Partners: The Internet connection required to use the Service, the Partner Devices and any associated charges incurred by the use of the Service are the exclusive financial and managerial responsibility of Partners. </span></strong><span style={{fontSize: '11.0pt', color: '#474747'}}>Transmitting and receiving real-time updates to and from the Partner Device, requires wifi connection. The expenses of such connection are as&nbsp;prescribed&nbsp;by the agreement between you and your communication service provider and according to its applicable terms of payment.</span></p>
        <p style={{textAlign: 'justify', textIndent: '-18.0pt', background: 'white', margin: '0cm 0cm 6.75pt 42.0pt'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>For Advertisers:</span></strong> <span style={{fontSize: '11.0pt', color: '#3d3d3d'}}>Please see the Advertising Terms and Conditions below.</span></p>
        <p style={{textAlign: 'justify', textIndent: '-18.0pt', background: 'white', margin: '0cm 0cm 6.75pt 42.0pt'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>Age</span></strong><span style={{fontSize: '11.0pt', color: '#474747'}}>.&nbsp;The Service is intended for use by users who are of the legal age required to hold a driving license. In any case, accounts of users under the age of 15 years will be cancelled and deleted by Payklever, upon receiving notice.</span></p>
        <p style={{textAlign: 'justify', textIndent: '-18.0pt', background: 'white', margin: '0cm 0cm 6.75pt 42.0pt'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>Privacy.&nbsp;</span></strong><span style={{fontSize: '11.0pt', color: '#474747'}}>While using the Service, personal information is &nbsp;provided by&nbsp;You&nbsp;or collected by Payklever as detailed in our Privacy Policy a</span><span style={{fontSize: '11.0pt', color: '#3d3d3d'}}>t https://www.payklever.com/privacy</span><span style={{fontSize: '11.0pt', color: '#474747'}}>. By accepting these Terms, you hereby acknowledge and agree to the collection, storage and use of your personal information by Payklever, subject to this section, the Privacy Policy and any applicable laws and regulation.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>THE SERVICE</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>The Service allows car drivers to pay for access to locations or for services (owners or manager of locations and service providers collectively referred to as “Partners”) via an RFID affixed to their vehicle. Partners use the Service to accept rapid, seamless payment from drivers’ vehicles without having to interact with the driver. The Service is provided mainly through the Software, an RFID sticker with an 8-digit alphanumeric code (the “Driver Device), and a switch, router, computer, camera and scanning mechanism (the “Partner Device”) (collectively the “Devices”).</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>You may use the Service solely for private and personal purposes. You may not: (i) offer to third parties a service of your own that uses the Service; (ii) resell the Service or Devices; (iii) offer to rent or lease the Software or Devices; or (iv) offer the Service to the public via communication or integrate it within a service of your own, without the prior written consent of Payklever. </span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>You may not copy, print, save or otherwise use data from the Site or the Service's database. This clause does not limit the use of the database as intended by the Software and for the purposes of private and personal use of the Service.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>When using the Service or the Site you may not engage in scraping, data mining, harvesting, screen scraping, data aggregating, and indexing. You agree that you will not use any robot, spider, scraper or other automated means to access the Site or the Service’s database for any purpose without the express prior written permission of Payklever.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>The Software may not be used in any way that is not expressly permitted by these Terms.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>USE RESTRICTIONS</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>There are certain&nbsp;types of conduct that are strictly prohibited on the Service. Your failure to comply with the provisions set forth below may result (at&nbsp;Payklever's&nbsp;sole discretion) in the termination of your access to the Service and may also expose you to civil and/or criminal liability.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>You may not, whether yourself or through any other means or person</span></strong><span style={{fontSize: '11.0pt', color: '#3d3d3d'}}>&nbsp;</span><span style={{fontSize: '11.0pt', color: '#474747'}}>: (i) copy, modify, adapt, translate, reverse engineer, decompile, or disassemble any portion of the Services, or in any way or publicly display, perform, or distribute them; (ii) make any use of the Content on any other website or networked computer environment for any purpose, or replicate or copy the Content without Payklever’s prior written consent; (iii) create a browser or border environment around the Content (e.g. no frames or inline linking); (iv) interfere with or violate any third party or other user's right to privacy or other rights, including copyrights and any other intellectual property rights of others, or harvest or collect personal information about visitors or users of the Service and/or Site without their express consent, including using any robot, spider, site search or retrieval application, or other manual or automatic device or process to retrieve, index, or data-mine; (v) defame, abuse, harass, stalk, threaten, or otherwise violate the legal rights of others, including others’ copyrights, and other intellectual property rights; (vi) transmit or otherwise make available in connection with the Service and/or Site any virus, worm, time bomb, web bug, spyware, or any other computer code, file, or program that may or is intended to damage or hijack the operation of any hardware, software, or telecommunications equipment, or any other actually or potentially harmful, disruptive, or invasive code or component; (vii) interfere with or disrupt the operation of the Service and/or Site, or the servers or networks that host the Service and/or Site or make the Service and/or Site available, or disobey any requirements, procedures, policies, or regulations of such servers or networks; (viii) sell, license, or exploit for any commercial purposes any use of or access to the Content and/or the Service and/or Site; (ix) frame or mirror any part of the Service and/or Site without Payklever’s prior express written authorization; (x) create a database by systematically downloading and storing all or any of the Content from the Service and/or Site; (xi) forward any data generated from the Service and/or Site without the prior written consent of Payklever; (xii) transfer or assign your Service accounts' password, even temporarily, to a third party; (xiii) use the Service and/or Site for any illegal, immoral or unauthorized purpose; (xiv) use the Site, the Service, or the Content for non-personal or commercial purposes without Payklever’s express prior written consent; or (xv) infringe or violate any of these Terms.</span></p>
        <p><span style={{fontSize: '11.0pt', fontFamily: '"Times New Roman",serif', color: '#3d3d3d'}}>&nbsp;</span><span style={{fontSize: '11.0pt', fontFamily: '"Times New Roman",serif', color: '#424242', background: 'white'}}>You acknowledge that you own, solely responsible or otherwise control all of the rights to the information you submit when creating an account; that the information is accurate; that use of the information you supply does not violate these Terms and will not cause injury to any person or entity; and that you will indemnify Payklever or its affiliates for all claims resulting from information you submit.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>&nbsp;</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>THE LICENSE</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>Payklever Service.&nbsp;</span></strong><span style={{fontSize: '11.0pt', color: '#3d3d3d'}}>&nbsp;</span><span style={{fontSize: '11.0pt', color: '#474747'}}>Payklever hereby grants you a free of charge, non-exclusive, time-limited, non-transferable, non-sub-licensable, revocable license to use the Service, (including the Software and the Devices) for non-commercial purposes, subject to these Terms.</span> <span style={{fontSize: '11.0pt', color: '#474747'}}>The Service is made available to users with the purpose of simplifying the payment and access experience, but WITHOUT ANY WARRANTY;&nbsp;without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>TERMINATION OF USE OF THE SERVICE</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>As a User, you may terminate your use of the Service at any time and for whatever reason. In order to cancel, you must send an email to </span><span style={{fontSize: '11.0pt', background: 'yellow'}}><a href="mailto:user-support@payklever.com">user-support@payklever.com</a></span><span style={{fontSize: '11.0pt', color: '#474747'}}> from the email address used to register your account, and enter “Cancel” in the subject-line. Payklever will use reasonable efforts to delete such information. Upon requesting cancellation, we will delete your account within 48 hours and any data to the extent it has not already been used permissibly to improve the Services.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Partners that wish to terminate the Service must give Payklever 6-months written notice by sending an email <span style={{background: 'yellow'}}>to partner-support@payklever.com</span>.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Payklever retains the right to block your access to the Service and discontinue your use of the Service, at any time and for any reason Payklever deems appropriate, at its sole and absolute discretion.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>If a user is terminated for violated these Terms, Payklever will make reasonable efforts to inform Partners of the termination. However, Payklever is not responsible for prohibiting access to your property or from using your services.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>COPYRIGHT</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>All intellectual property rights in and to the Site, the Service and its database, including copyrights, trademarks, industrial designs, patents and trade secrets – are the exclusive property of Payklever.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>"Payklever", the Payklever logo, and other trade and/or service marks are the property of Payklever or its affiliates and you may not use such logos or marks for any purpose that is not expressly authorized in these Terms without the prior written consent of Payklever.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Users and Partners are granted a license to use the Payklever mark on their properties, on their websites, and in their communications so long as the representation reflects the Website, the Service and the Software and is consistent with these Terms.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>PAYMENT AND REFUND TERMS</span></strong></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>In order to use the Service as a Driver, Partner or Advertiser, you must submit a credit card, debit card, ACH-enabled checking or savings account, or other payment method (a “<strong>Payment Method</strong>”) through which you will pay all charges incurred or receive all funds earned in connection with the Service.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>When you provide a Payment Method in connection with the Service:</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>You confirm that you are permitted to use that Payment Method, and you authorize Payklever and/or Payklever’s third-party payment processing service, Stripe.com (“Stripe”) to confirm that your Payment Method is in good standing with the issuing financial institution and/or carrier (as applicable), including, but not limited to, by submitting a request for a payment authorization and/or a low dollar credit and/or debit to the Payment Method, in accordance with the relevant card association or carrier rules as applicable. </span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>You authorize Stripe to store the Payment Method, along with other related transaction information, and bill the designated Payment Method for all charges accrued on a daily basis during the Service term, and if applicable, on a recurring basis.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Your Payment Method will be billed at the time of purchase or shortly thereafter. &nbsp;If you pay by debit card and your payment results in an overdraft or other fee from your bank, Payklever shall bear no responsibility.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>You are obligated to fulfill your payment obligations for the Services in a timely fashion. If you fail to do so, we will be entitled to a compensation equaling the amount due plus interest at 5% per month, until we terminate your account. In addition, if you fail to make any payment to Payklever when due under these Terms, Payklever will be entitled to cancel the Service, without prior notice, and you will not have any claims against Payklever in connection therewith.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Payklever reserves the right to issue refunds or credits at its sole discretion. However, if you believe you were overcharged or that there is an error with your billing, then you must make a claim for a refund within 10 days of the charge by sending an email to </span><span style={{fontSize: '11.0pt', background: 'yellow'}}><a href="mailto:user-support@payklever.com">user-support@payklever.com</a></span><span style={{fontSize: '11.0pt', color: '#333333', background: 'yellow'}}>.</span></p>
        <p style={{background: 'white'}}><strong><span style={{fontSize: '11.0pt', color: '#333333'}}>DEVICES</span></strong></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>If a Device is stolen or damaged, you must inform Payklever at </span><span style={{fontSize: '11.0pt'}}><a href="mailto:partner-support@payklever.com">partner-support@payklever.com</a></span><span style={{fontSize: '11.0pt', color: '#333333'}}> as soon as possible. Payklever is not responsible for any unauthorized charges in any event, including theft or misplacement. It is the responsibility of all users to ensure their Devices are working as intended, in your sole possession. Should your Device malfunction, you must inform Payklever and you are prohibited from attempting to repair independently of Payklever. Additionally, Payklever is not obligated to replace any stolen, damaged or lost Devices. Replacement fees will be assessed at the time. For all Partner Devices that have been damaged, stolen, or misplaced, a fine will be assessed at the time of the incident and imposed, payable 30 days from the date of the incident, whether or not you wish to continue using the Services.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>You are prohibited from making a duplicate or attempt to recreate any Devices for any purpose. Upon duplicating, recreating or misusing the Devices, you are exclusively liable for any and all damage that occurs as a result.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Our Devices only scan vehicles of users that have opted-into our Services. Therefore, all data collected is done so permissibly pursuant to our Terms. We do not collect data on individuals or vehicles that have not opted-into the Services.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>LIMITATION OF LIABILITY AND WARRANTY</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>PAYKLEVER PROVIDES THE SERVICE AND DEVICES FOR USE ON AN "AS IS" AND "AS AVAILABLE" BASIS.&nbsp; WE HEREBY DISCLAIM ALL WARRANTIES AND REPRESENTATIONS, EITHER EXPRESS OR IMPLIED, WITH RESPECT TO THE SERVICE, INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE, FEATURES, QUALITY, NON-INFRINGEMENT, TITLE, COMPATIBILITY, PERFORMANCE, SECURITY OR ACCURACY.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>You agree and acknowledge that you assume full, exclusive and sole responsibility for the use of and reliance on the Service, and you further agree and acknowledge that your use of or reliance on the Service is made entirely at your own risk. You further acknowledge that it is your responsibility to comply with all applicable laws, Partner facility rules and regulations, while using the Service. </span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>We do not warrant that the Service or Devices will operate in an uninterrupted or error-free manner, or that it will always be available or free from all harmful components, or that it is safe, secured from unauthorized access to&nbsp;Payklever's&nbsp;computers, immune from damages, free of malfunctions, bugs or failures, including, but not limited to hardware failures, Software failures and Software communication failures, originating either in Payklever or any of its providers. </span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Drivers are solely responsible for installing the Driver Device onto their vehicle. Payklever cannot be held responsible for any distractions or impairment of vision due to the location of the Driver Device.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>PAYKLEVER, INCLUDING ITS OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS AND AGENTS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL OR CONSEQUENTIAL DAMAGE, OR ANY OTHER DAMAGE, AND LOSS (INCLUDING LOSS OF PROFIT AND LOSS OF DATA), COSTS, EXPENSES AND PAYMENTS, EITHER IN TORT, CONTRACTUAL, OR IN ANY OTHER FORM OF LIABILITY, ARISING FROM, OR IN CONNECTION WITH THE USE OF, OR THE INABILITY TO USE THE SERVICE, OR FROM ANY FAILURE, ERROR, OR BREAKDOWN IN THE FUNCTION OF THE SERVICE, OR FROM ANY FAULT, OR ERROR MADE BY OUR STAFF OR ANYONE ACTING ON ITS BEHALF, OR FROM YOUR RELIANCE ON THE CONTENT OF THE SERVICE, INCLUDING, WITHOUT LIMITATION, CONTENT ORIGINATING FROM THIRD PARTIES, OR FROM ANY COMMUNICATION WITH THE SERVICE, OR WITH OTHER USERS ON OR THROUGH THE SERVICE, OR FROM ANY DENIAL OR CANCELLATION OF YOUR USER ACCOUNT, OR FROM RETENTION, DELETION, DISCLOSURE AND ANY OTHER USE OR LOSS OF YOUR CONTENT ON THE SERVICE. IN ANY EVENT, YOUR SOLE REMEDY WILL BE LIMITED TO CORRECTING SUCH ERRORS, OR MALFUNCTIONS, AND IN LIGHT OF THE RELEVANT CIRCUMSTANCES.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#3d3d3d'}}>&nbsp;</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>LINKS AND COMMERCIAL INFORMATION IN THE SOFTWARE</span></strong></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{fontSize: '11.0pt', fontFamily: '"Times New Roman",serif', color: '#474747'}}>The Service may include commercial information or advertisements (“Ads”). The Ads may be sent via text messages, notifications, and/or emails from time to time. Payklever may post Ads on the Service, or may enable third parties to place Ads, and therefore Payklever cannot and does not guarantee the reliability or accuracy of third party Ads. Payklever does not endorse the content of third party Ads</span><span style={{fontSize: '11.0pt', fontFamily: '"Times New Roman",serif', color: '#3d3d3d'}}>, nor shall it be expected to honor any promotions offered in Ads. Ads are submitted by third-parties and Partners, some of which have no relation to Payklever’s operations. </span><span style={{fontSize: '11.0pt', fontFamily: '"Times New Roman",serif', color: '#474747'}}>Additionally, notwithstanding the aforementioned disclaimers, Payklever will not be liable for any form of liability arising from your reliance on, or in connection with, the use of the content of Ads posted on the Service.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Insofar as the Software includes links to services or applications not operated or managed by Payklever, Payklever will not be liable for any form of liability arising from your reliance on, or in connection with, the content of such services and applications or any information provided by them, including but not limited to its completeness, accuracy, correctness or it being up-to-date. Payklever will not be liable for any direct or indirect damage, monetary or otherwise, arising from your use of or your reliance on the content of goods or services you have accessed via Ads or other links on the Software.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>We use the data collected permissibly pursuant to the Terms to serve you personalized Ads, based on your route history, website browsing behavior, or geolocation. You may request this data to be deleted or for Ads to cease using your personalized information by sending us an email.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>YOU MUST NOT ATTEMPT TO VIEW OR CLICK ON ANY ADS WHILE OPERATING A VEHICLE. YOU ALONE ARE RESPONSIBLE FOR DRIVING RESPONSIBLY, AND YOU ACKNOWLEDGE AND AGREE THAT IN THE EVENT THAT YOU VIOLATE THE FOREGOING PROVISION, THE THIRD PARTY ADVERTISERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL OR CONSEQUENTIAL DAMAGE, OR ANY OTHER DAMAGE, AND LOSS (INCLUDING LOSS OF PROFIT AND LOSS OF DATA), COSTS, EXPENSES AND PAYMENTS, EITHER IN TORT, CONTRACTUAL, OR IN ANY OTHER FORM OF LIABILITY, ARISING FROM, OR IN CONNECTION WITH THE DISPLAY OF THE ADS ON THE SERVICE OR YOUR VIEWING OF THE ADS ON THE SERVICE.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>BREACH AND INDEMNITY</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Without derogating from any applicable law, you agree to indemnify and hold harmless Payklever and its employees, officers, directors and agents, as well as all third party advertisers from and against all claims, damages, expenses, losses and liabilities that arise as a result of your violation of these Terms. In view of the fact that the Service is provided to you free-of-charge, this indemnity is intended to cover all expenses, payments, loss, loss of profits or any other damage, direct or indirect, monetary or non-monetary, incurred by Payklever, its employees, officers, directors or agents as a result of your violation of the Terms, including but not limited to legal expenses and attorney fees.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>&nbsp;</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>PRIVACY</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Payklever respects your privacy during your use of the Software and the Service. Our updated privacy policy pertaining to the Software is readily accessible at&nbsp;</span><span style={{fontSize: '11.0pt', color: '#3d3d3d'}}>https://www.payklever.com/privacy</span><span style={{fontSize: '11.0pt'}}> <span style={{color: '#474747'}}>and is an integral part of these Terms. Since the privacy policy is subject to periodic updates, it is recommended that you periodically review the policy for updates.</span></span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>&nbsp;</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>MODIFICATIONS TO THE SERVICE &amp; DEVICES</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Payklever may, either partially or in its entirety and without being obligated to provide prior notice – modify, adapt or change the Software, the Service's features, the Devices, user interface and design, the extent and availability of the contents in the Service and any other aspect related to the Service. You will have no claim, complaint or demand against Payklever for applying such changes or for failures incidental to such changes.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Partners must grant Payklever, its affiliates and its contractors non-revocable access to its property to install, service and maintain Partner Devices. Payklever will make all reasonable efforts to inform users of a software update that may prevent users from using the Service. Payklever will provide routine maintenance on the Service which may inadvertently cause the Service to be inaccessible. You hereby agree to hold Payklever harmless for all interruptions its Service may cause your operations.</span></p>
        <p><span style={{fontSize: '11.0pt', fontFamily: '"Times New Roman",serif'}}>&nbsp;</span></p>
        <p><strong><span style={{fontSize: '11.0pt', fontFamily: '"Times New Roman",serif'}}>TERMS SPECIFIC TO ADVERTISERS</span></strong></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>These Payklever Advertising Terms and Conditions (the "<strong>Ad</strong><strong>&nbsp;Terms</strong>") are entered into by Payklever and businesses placing Ads (“Advertisers”) with the Service. The Terms shall apply to all matters not specifically addressed in the Ad Terms.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>These Ad Terms are what govern your use and purchase of any advertising space from Payklever for use and display of your advertising materials and related technology on the Service.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Personal data used in connection with the Service is controlled and processed by Payklever according to these Ad Terms, the Terms, and the Privacy Policy. </span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Advertisers accept the Terms <strong>by purchasing advertising space with the Service</strong>. In this case, your use of the Payklever and placing Ads will be deemed acceptance of the Terms from that point onwards.</span></p>
        <h2 style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Advertising with the Service</span></h2>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>In order to place Ads, you will be required to provide detailed contact information, and a detailed description of the products and services that will appear in your Ads. You hereby agree that any information you provide to Payklever is accurate, correct and current.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>You agree not to access, contact, or attempt to access or contact Partners or Drivers by for any purpose related to Payklever unless we have authorized contact for such purpose.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>You agree that you will not engage in any activity that interferes with or disrupts, or otherwise attempt to corrupt the integrity of, the Service, the Software or the Devices.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>You agree that you are solely responsible for, and Payklever has no liability towards you or any third party, for any breach of these Ad Terms or Terms and/or the consequences of any such breach and/or the use of the Service provided hereunder, including any loss or damage Payklever may incur or suffer as a result of such breach.</span></p>
        <h2 style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Advertisements Policy</span></h2>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Please refer to the Advertising Privacy Policy located at ________ </span><span style={{fontSize: '11.0pt', color: '#333333'}}>to review the terms governing the information disclosed to You and by You.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>You agree that you are solely responsible for (and that Payklever will have no responsibility to you or to any third party for) any Ads that you create, post, upload, transmit or display through the Service and for the consequences of your actions (including any loss or damage which Payklever may suffer) by doing so. Payklever does not endorse the Ads you provide on the Service, and the accuracy, content, and obligation to honor any commitments in connection with the Ads is yours alone.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>You are also solely responsible for ensuring that you have all necessary rights, licenses, consents and permissions from the applicable parties to submit and display Ads on the Service.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>If you provide to Payklever, upload or display an Ad that (a) violates the Ad Terms or Terms, (b) infringes another party’s intellectual property rights, or (iii) violates another party’s privacy rights, that will constitute a breach of the Ad Terms, and Payklever will have the right to remove the Ad and suspend or terminate your access to the Service. You may also be obligated to indemnify Payklever in connection with such breach.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>You acknowledge and agree that placing your Ads with the Service is not guaranteed and the display, timing, and frequency of display of your Ads is determined by Payklever in its sole discretion, and you hereby authorize Payklever to manage and display your Ads with the Service in its sole discretion. Payklever may elect to refrain from displaying your Ads or allowing you to utilize the Service in its sole discretion.</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Payklever takes all reasonable efforts to verify audience demographics, traffic count, and Ad reach. However, such metrics change on a sometimes hourly basis and can be subject to fraud. Payklever cannot be held liable for misrepresenting the description of audiences.</span></p>
        <h2 style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Advertisement Specific Payment Terms</span></h2>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>The Payment and Refund Terms incorporated herein shall apply to Advertisers. Additionally, the following Ad Terms apply to Advertisers paying Payklever.</span></p>
        <p style={{background: 'white'}}><strong><span style={{fontSize: '11.0pt', color: '#333333'}}>Cancellations</span></strong><span style={{fontSize: '11.0pt', color: '#333333'}}>. Unless otherwise agreed between us in writing, Ad placements may be cancelled on a monthly basis. All Ads that have not been cancelled by the 15<sup>th</sup> of the current month will automatically renew for the subsequent month.</span></p>
        <p style={{background: 'white'}}><strong><span style={{fontSize: '11.0pt', color: '#333333'}}>Cancellation Notice</span></strong><span style={{fontSize: '11.0pt', color: '#333333'}}>. You must cancel an Ad by sending an email to Payklever at <span style={{background: 'yellow'}}>admin@payklever.com.</span></span></p>
        <p style={{background: 'white'}}><strong><span style={{fontSize: '11.0pt', color: '#333333'}}>Pricing</span></strong><span style={{fontSize: '11.0pt', color: '#333333'}}>. Payklever reserves the right to adjust the pricing of the Ads from time to time, in its sole discretion. Ads which were placed prior to the price change are not subject to the same, but all new orders shall reflect the updated prices.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>TERMINATION OF SERVICE</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Payklever may, at any time, terminate the provision of the Service in its entirety or any part thereof, temporarily or permanently, at its sole discretion.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>MODIFICATIONS OF THESE TERMS</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Payklever may modify these Terms from time to time. If fundamental changes are introduced, a notice will be posted in the updated version of the Software as well as on the Service's home page on the Site. Your continued use of the Service after the Terms have been modified signifies your assent to the updated Terms. If you dissent to the updated Terms or to any term within them, you must discontinue all further use of the Software.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>GOVERNING LAW AND JURISDICTION</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>These Terms, the Software and the Service will be governed solely by the laws of the State of Florida, without giving effect to any conflicts of law principles. Any dispute, claim or controversy arising out of, connected with or relating to these Terms, the Software and the Service, will be under the exclusive jurisdiction of the competent court in Miami-Dade, Florida.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>&nbsp;</span></p>
        <p style={{margin: '0cm', marginBottom: '.0001pt', background: 'white'}}><strong><span style={{fontSize: '11.0pt', color: '#424242'}}>ARBITRATION</span></strong></p>
        <p style={{margin: '0cm', marginBottom: '.0001pt', background: 'white'}}><span style={{fontSize: '11.0pt', color: '#424242'}}>&nbsp;</span></p>
        <p style={{background: 'white', margin: '0cm 0cm 7.5pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#424242'}}>Except as regarding any action seeking equitable relief, any controversy or claim arising out of or relating to these Terms or this Service shall be settled by binding arbitration in accordance with the commercial arbitration rules, in effect at the time the proceedings begin, of the American Arbitration Association. Any such controversy or claim shall be arbitrated on an individual basis, and shall not be consolidated in any arbitration with any claim or controversy of any other party. The arbitration shall be held in Miami, Florida, USA.</span></p>
        <p style={{background: 'white', margin: '0cm 0cm 7.5pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#424242'}}>All information relating to or disclosed by any party in connection with the arbitration of any disputes hereunder shall be treated by the parties, their representatives, and the arbitrator as proprietary business information. Such information shall not be disclosed by any party or their respective representatives without the prior written authorization of the party furnishing such information. Such information shall not be disclosed by the arbitrator without the prior written authorization of all parties. Each party shall bear the burden of its own counsel fees incurred in connection with any arbitration proceedings.</span></p>
        <p style={{background: 'white', margin: '0cm 0cm 7.5pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#424242'}}>Judgment upon the award returned by the arbitrator may be entered in any court having jurisdiction over the parties or their assets or application of enforcement, as the case may be. Any award by the arbitrator shall be the sole and exclusive remedy of the parties. The parties hereby waive all rights to judicial review of the arbitrator's decision and any award contained therein.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>LIMITATIONS</span></strong></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>Should you desire to file any cause of action against Payklever, arising out of or related to the Software, Service, or Devices, you must do so within one (1) year of the day you become aware of the cause of action. Failure to file a lawsuit within the aforementioned timeframe will bring about the permanent barring of the cause of action, and will constitute your complete and final waiving of the lawsuit. </span><u><span style={{fontSize: '11.0pt', color: '#333333'}}>No Limitation</span></u><span style={{fontSize: '11.0pt', color: '#333333'}}>. Nothing in these Terms will limit a party's ability to seek equitable relief.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>ENTIRE AGREEMENT</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>These Terms, together with the policies that are an integral part of these Terms and the Privacy shall all constitute the entire and complete agreement between you and Payklever concerning the Payklever Service. In the event of an inconsistency between these Terms and the synopsis of terms presented to the user during account setup, in the case of Users, or system installation, in the case of Partners, these Terms shall prevail.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><strong><span style={{fontSize: '11.0pt', color: '#474747'}}>NO LEGAL RELATIONSHIP</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '0cm 0cm 6.75pt 0cm'}}><span style={{fontSize: '11.0pt', color: '#474747'}}>These Terms and your use of the Service do not, and shall not be construed as creating any relationship, partnership, joint venture, employer-employee, agency, or franchisor-franchisee relationship in any way and of any kind between the parties hereto. Your use of the Service is intended for your enjoyment and benefit and the provision of the Service to you (subject to your compliance with these Terms) constitutes the sole and sufficient consideration that you are entitled to receive.</span></p>
        <p style={{background: 'white'}}><u><span style={{fontSize: '11.0pt', color: '#333333'}}>Notices</span></u><span style={{fontSize: '11.0pt', color: '#333333'}}>. All legal notices shall be sent to:</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>PAKYLEVER, INC</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>1200 Brickell Ave, </span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Suite 800</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>Miami, Florida 33131</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>&nbsp;</span></p>
        <p style={{background: 'white'}}><span style={{fontSize: '11.0pt', color: '#333333'}}>All electronic written communications for notices shall be sent to <span style={{background: 'yellow'}}>admin@payklever.com.</span> </span></p>
        <p style={{background: 'white'}}><u><span style={{fontSize: '11.0pt', color: '#333333'}}>Force Majeure</span></u><u><span style={{fontSize: '11.0pt', color: '#333333'}}>.</span></u><span style={{fontSize: '11.0pt', color: '#333333'}}> Except for payment obligations, no party or its affiliates is liable for inadequate performance to the extent caused by a condition that was beyond its reasonable control.</span></p>
        <p style={{background: 'white'}}><u><span style={{fontSize: '11.0pt', color: '#333333'}}>No Waiver</span></u><span style={{fontSize: '11.0pt', color: '#333333'}}>. Neither party will be treated as having waived any rights by not exercising (or delaying the exercise of) any rights under the Terms.</span></p>
        <p style={{background: 'white'}}><u><span style={{fontSize: '11.0pt', color: '#333333'}}>Severability</span></u><span style={{fontSize: '11.0pt', color: '#333333'}}>. If any provision of the Terms is found unenforceable, the remaining Terms will remain in full force and effect.</span></p>
        <p><strong><span style={{fontSize: '11.0pt', fontFamily: '"Times New Roman",serif'}}>&nbsp;</span></strong></p>
        <p>&nbsp;</p>


    </div> )}</I18n>)
  }

}

export default Login;
