import React, { Component } from 'react';
import { I18n } from 'react-i18next';

class PrivacyPolicy extends Component {
  render() {
    return (
      <I18n>{(t, { i18n }) => (<div className="shadow-lg p-5 bg-white rounded">


        <p style={{textAlign: 'justify', background: 'white'}}><strong><span style={{fontSize: '16.0pt',  color: '#333333'}}>Payklever Advertiser Privacy Policy</span></strong></p>
        <p style={{textAlign: 'justify'}}><span style={{ color: '#3d3d3d'}}>As of May 1, 2018:</span></p>
        <p style={{textAlign: 'justify'}}><span style={{ color: '#3d3d3d'}}>Payklever Inc. respects your privacy. Payklever and its affiliates (“Payklever”, the “Company”, “we”, “us” or “our”) have created </span><span style={{ color: 'black'}}>a hands-free payment method for drivers (“Users”) to conduct transactions from their cars via </span><span style={{ color: '#0070c0'}}><a href="http://www.payklever.com"><span style={{color: '#0070c0'}}>www.payklever.com</span></a></span> <span style={{ color: '#3d3d3d'}}>(the “Website”), and for businesses to promote their products or services to Users through advertisements (the businesses advertising shall be referred to herein as “Advertisers”). This policy explains the privacy practices of Payklever as they relate to the purchase and display of advertisements from Payklever (the "Advertising Services"), and how Payklever collects and uses your personal information and the rights and options available to you. </span><span style={{ color: 'black'}}>Any capitalized term not expressly defined herein shall have the same meaning as given </span><span style={{ color: 'black'}}>in the Terms of Use, or as labeled or identified on the Website.</span></p>
        <p style={{textAlign: 'justify'}}><span style={{fontFamily: '"Times New Roman",'}}>&nbsp;</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><strong><span style={{ color: '#3d3d3d'}}>Your use of the Advertisement Services is subject to the Terms of Use and Privacy Policy and indicates your consent to them.</span></strong></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>Changes to the Privacy Policy: Payklever may from time to time change the terms of this Privacy Policy. If Payklever amends this Privacy Policy to comply with legal requirements, the amendments will become effective immediately upon their initial posting, or as required.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>You agree to be bound by any of the changes made in the terms of this Privacy Policy. Continuing to use the Advertising Services will indicate your acceptance of the amended terms. If you do not agree with any of the amended terms, you must avoid any further use of the Advertising Services.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>This Privacy Policy is incorporated as part of the Payklever Terms of Use&nbsp;(the “Terms of Use” or the “Terms”).</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>In this Privacy Policy, the term “Personal Information” means any information collected by us or provided by you that, with reasonable efforts, may be used to identify you, which may include full name, date of birth, company name, an address, a phone number, and an email address. In addition to collecting Personal Information, we also will collect information on your current customers, your marketing goals and strategies, and any other marketing data which you provide us. Providing Payklever with false, incorrect, or out-dated information is a violation of the Terms of Use and will impair Payklever’s ability to provide you with the Advertising Services.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '13.5pt 0cm 6.75pt 0cm'}}><strong><span style={{ color: '#3d3d3d'}}>Payment Information</span></strong></p>
        <p style={{textAlign: 'justify', background: 'white'}}><span style={{ color: '#333333'}}>When you create an</span><span style={{ color: '#333333'}}>, you will be required to provide Payklever with certain details, such as your full name, billing address, the last four digits of your social security, your employer identification or Tax ID number, and on some occasions more. You will be required to provide Payklever with your payment details, including credit card details (credit card number, security code and expiration date). To protect your privacy, your payment details may not be stored on Payklever's systems but rather on a third-party online payment gateway that assists Payklever in the authentication, authorization, charge and maintenance of your payment details for the use of the Advertising Services. This is with the provision that such gateway is subject to applicable standards and regulations with respect to the holding of personal information and the processing of online payments.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><strong><span style={{ color: '#3d3d3d'}}>Uses of information</span></strong></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>Payklever may use information collected from or provided by you for the following purposes:</span></p>
        <ul style={{marginTop: '0cm'}}>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To provide you with the Advertising Services;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To improve the experience of Users and other Advertisers;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To provide you with support and handle requests and complaints;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To send you updates, notices, announcements, and additional information related to the Advertising Services;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To send you marketing material. At any time you may choose not to receive such material by <span style={{background: 'yellow'}}>_______</span>. In any case, Payklever will not knowingly share your personal information with any advertisers, without your explicit consent and as allowed for under this Privacy Policy;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To create aggregated and/or anonymous data (where such data does not enable the identification of a specific user);</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To conduct surveys and questionnaires;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To enforce the Terms of Use;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To contact you in any way when Payklever believes it to be necessary;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To comply with any applicable law and assist law enforcement agencies under any applicable law, when Payklever has a good faith belief that Payklever’s cooperation with the law enforcement agencies is legally mandated or meets the applicable legal standards and procedures;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To prevent fraud, misappropriation, infringements, identity theft and other illegal activities and misuse of the Advertising Services;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To manage bugs and malfunctions;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To take any action in any case of dispute, or legal proceeding of any kind between you and Users, or between you and other Advertisers, or third-parties with respect to, or in relation to the Advertising Services or any other services provided under through Payklever;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>For any other purposes provided under this Privacy Policy and the Terms of Use.</span></li>
        </ul>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>Further information may be collected when Payklever exchanges communications with you, for example, if you submit a request, contact Payklever’s support team, or report a violation to the abuse team.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '13.5pt 0cm 6.75pt 0cm'}}><strong><span style={{ color: '#3d3d3d'}}>Website Behavior Data</span></strong></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>Payklever collects information about the use of the Advertising Services and information from the device you have used to access Payklever, the frequency and scope of your use of the Advertising Services, the duration of your sessions, browser, browser version, browser dimensions, device name, operating system type, operating system version, battery usage, information that you viewed, content that you use or create, advertisements that you view or click on, your communications with Partners and third-parties, the Internet protocol (IP) address and the name of the domain that serve you to access the Services, and the geographic location of the device that you are using to log-in and use Payklever on.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '13.5pt 0cm 6.75pt 0cm'}}><strong><span style={{ color: '#3d3d3d'}}>Accessing the Services</span></strong></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>In order to access certain features of the Advertising Services, you will need to connect a payment method (see our </span><u><span style={{ color: '#0070c0'}}>Terms of Use</span></u> <span style={{ color: '#3d3d3d'}}>regarding storing payment information).</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>Payklever may also establish and require from time to time additional or different means of identification and authentication for logging in and accessing the Advertising Services or for accessing certain features or designated sections of the Advertising Services.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>Your log-in details are your responsibility. You are fully accountable for any use or misuse of your Account and personal details as a result of conveying your details to someone else. You must maintain your log-in details in absolute confidentiality and avoid disclosing them to others. It is your responsibility to frequently update your password. </span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '13.5pt 0cm 6.75pt 0cm'}}><strong><span style={{ color: '#3d3d3d'}}>Sharing User Information</span></strong></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>Payklever does not sell, rent or lease your Personal Information to third parties for marketing purposes. Payklever will not share your Personal Information with others, without your consent, except for the following purposes and to the extent necessary in Payklever’s good-faith discretion:</span></p>
        <ul style={{marginTop: '0cm'}}>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>As necessary for the operation of the Advertising Services;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{ color: '#333333'}}>When you use the Advertising Services, when you take part in content-related activities, when it is necessary to facilitate the functionality of the Advertising Services and when it is necessary to manage and administer any other service Payklever provides;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>If Payklever reasonably believes that you have breached the Terms of Use, or abused your rights to use the Advertising Services, or performed any act or omission that Payklever reasonably believes to be violating any applicable law, rules, or regulations. Payklever may share your information in these cases, with law enforcement agencies and other competent authorities and with any third-party as may be required to handle any result of your wrongdoing;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>If Payklever is required, or reasonably believes that it is required by law to share or disclose your information;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>In any case of dispute, or legal proceeding of any kind between you and Payklever, or between you and other users with respect to, or in relation with the Advertising Services;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>If Payklever organizes the operation of the Advertising Services within a different framework, or through another legal structure or entity, or if Payklever is acquired by, or merged into or with another entity, provided however, that those entities agree to be bound by the provisions of this Privacy Policy, with respective changes taken into consideration;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To store your data on servers;</span></li>
          <li style={{color: '#3d3d3d', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>To collect, hold and manage your Personal Information through cloud based or hosting services or a third-party or a party affiliated or connected to Payklever, as reasonable for business purposes;</span></li>
          <li style={{color: 'black', marginBottom: '6.75pt', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{ color: '#3d3d3d'}}>Payklever may also share Personal Information with companies or organizations connected or affiliated with Payklever, such as, companies Payklever reasonably believes will become an Advertiser, subsidiaries, and sister-companies. Personal Information may also be shared with Payklever’s other partners and service providers to process it for us, based on our instructions and in compliance with this policy and any other appropriate confidentiality </span><span style={{fontFamily: '"Times New Roman",'}}>and security measures.</span></li>
        </ul>
        <p style={{textAlign: 'justify', background: 'white', margin: '13.5pt 0cm 6.75pt 0cm'}}><strong><span style={{ color: 'black'}}>Personal Information</span></strong></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>This information is held by Payklever associated with your Account and for such limited period of time as is necessary in order for Payklever to be able to use the information for the purposes described in this Privacy Policy. At the end of this period of time, Payklever will then anonymize and aggregate or delete your location and route information.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>If you would like us to delete your Account and your personal information, please send an email to <span style={{color: 'black'}}><a href="mailto:admin@payklever.com">admin@payklever.com</a></span> with the subject line “Delete Account” from the email used to register your Account.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>On receiving such a request, Payklever will use reasonable efforts to delete such information. However, some information that has been collected and anonymized may not be able to be removed from our system.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>If you find that the information associated with your Account is not accurate, complete or updated, then you must make all necessary changes to correct it as soon as you have discovered it.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '13.5pt 0cm 6.75pt 0cm'}}><strong><span style={{ color: 'black'}}>Payklever Aggregated Data</span></strong></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>Payklever may use anonymous, statistical or aggregated information (including anonymous location information), in a form that does not enable the identification of a specific user, to properly operate the Services, to improve the quality of the Services, to enhance your experience, to create new services and features, including customized services, to change or cancel existing content or service, and for further internal, commercial and statistical purposes (including advertising).</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>Payklever may also use anonymous, statistical or aggregated information collected on the Advertising Services, in a form that does not enable the identification of a specific user, by posting, disseminating, transmitting or otherwise communicating or making available such information to the Advertising Services service providers, partners and any other third-party. For example, ads analysis may be provided to other third-party advertisers.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '13.5pt 0cm 6.75pt 0cm'}}><strong><span style={{ color: 'black'}}>Cookies</span></strong></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>Payklever may use cookies on the Advertising Services for various purposes, such as to save you the need to re-enter your email and password each time you log-in, to facilitate the use of the Website, to collect statistical information, to verify information, and to customize the Website to your personal preferences and for information security purposes.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>Cookies either expire when the session ends and you exit your browser or may be saved on your smart device or computer’s hard drive. If you wish to block the Website’s cookies, then please use the help button in your browser and follow the necessary instructions.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '13.5pt 0cm 6.75pt 0cm'}}><strong><span style={{ color: 'black'}}>Advertisements and Promotions</span></strong></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>Payklever may permit, solicit or contract certain other companies to conduct Advertisements and Promotions through the Advertising Services.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>The information and advertisements that you see when accessing the Advertising Services may be targeted on the basis of:</span></p>
        <ul>
          <li style={{color: 'black', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>Geographic or contextual information which we collect from you, including information described in this Privacy Policy;</span></li>
          <li style={{color: 'black', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>Information received from third-party partners; and,</span></li>
          <li style={{color: 'black', textAlign: 'justify', tabStops: 'list 36.0pt', background: 'white'}}><span style={{fontFamily: '"Times New Roman",'}}>Information received from Partners.</span></li>
        </ul>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>You hereby agree that we may provide such information and advertisements targeted on the basis of your address, location, Website access locations and more.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: 'black'}}>When you visit a third-party website </span><span style={{ color: '#3d3d3d'}}>from the Website, such third-party may use cookies on your computer. The third-party’s use of cookies is subject to their own privacy policies and not to this Privacy Policy.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>The Service includes text and email messaging for transactions and other notifications which gives Payklever the authorization to send marketing messages from us or other Advertisers. You hereby agree that we may use text messaging and emails for the purpose of informing you regarding products or services, which may interest you.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>It is clarified that we are not responsible for the content of said advertisements and the products delivered or services rendered thereby by third parties and you irrevocably and unconditionally agree that we shall not be held responsible or liable in connection thereof.</span></p>
        <p style={{textAlign: 'justify', background: 'white', margin: '13.5pt 0cm 6.75pt 0cm'}}><strong><span style={{ color: '#3d3d3d'}}>Information Security</span></strong></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>Payklever considers information security to be a top priority. Payklever implements systems, applications and procedures to secure your personal information, to minimize the risks of theft, damage, loss of information, or unauthorized access or use of information. However, these measures are unable to provide absolute assurance. Therefore, although Payklever takes great efforts to protect your personal information, Payklever cannot guarantee and you cannot reasonably expect that Payklever’s databases will be immune from any wrongdoings, malfunctions, unlawful interceptions or access, or other kinds of abuse and misuse.</span></p>
        <p style={{textAlign: 'justify', background: 'white'}}><span style={{ color: '#333333'}}>If you believe that your privacy has been compromised by any person, in the course of using the Services, then please contact Payklever at:&nbsp;</span><span style={{fontFamily: '"Times New Roman",'}}><a href="mailto:admin@payklever.com">admin@payklever.com</a></span><span style={{fontFamily: '"Times New Roman",'}}>.</span></p>
        <p style={{marginBottom: '6.75pt', textAlign: 'justify', background: 'white'}}><span style={{ color: '#3d3d3d'}}>&nbsp;</span></p>
        <p>&nbsp;</p>


    </div> )}</I18n>)
  }

}

export default PrivacyPolicy;
